<?php
	if(!defined("MYHOST"))
		define("MYHOST","127.0.0.1");
	if(!defined("MYUSER"))
		define("MYUSER","root");
	if(!defined("MYPASS"))
		define("MYPASS","");
	if(!defined("MYDB"))
		define("MYDB","slash");
?>